### PR TITLE
OpenModelica compatibility

### PR DESCRIPTION
**Pull request by Mathadon**
I made some changes that allow opening IDEAS in OpenModelica. Most changes were due to inconsistent package.order files. Many files were removed because they were still present in the repository while they are no longer in the library. For instance there was a folder Battery and a folder Batteries. The old folder was removed. This is however based on my interpretation and since I don't use the electrical library a double-check may be helpful.

I also updated reference results and added simulation statistics that were added in the last version of BuildingsPy.

@rubenbaetens @vanroyj can you verify that no wrong folders/files were removed?

### CODE REVIEW

**Comment by saroele** [comment]
So IDEAS can be opened in OM now?  Any idea on the % of examples that can be ran?

**Comment by Mathadon** [comment]
No idea :p
You should at least be able to open the library in OM.

**Comment by saroele** [comment]
Great, that's where it starts :-)

**Comment by rubenbaetens** [comment]
Allright ! i'll check it later today.

**Comment by Mathadon** [comment]
bump

**Comment by Mathadon** [comment]
Fixed merge conflicts.

**Comment by Mathadon** [comment]
this was merged into #350

**Pull request closed without merging**
