### PR TITLE
Issue398 material order

### PR DESCRIPTION
**Pull request by damienpicard**
This handle #394 .

The changes are:
1) creation of common partial for building envelope components (walls, floors, ceilings, ...)
2) flip the layMult to connect port_a to propsBus_a
3) add check for floor and ceiling inclination
4) Combine the different monolayer models into fewer models.

### CODE REVIEW

**Comment by damienpicard** [comment]
@Mathadon and @rubenbaetens : it would be good if you can have a critical look at the changes. As we are allowed to include backward non-compatible changes, this is an unique chance for big clean up :)

**Comment by damienpicard** [comment]
The unit test gives different results. @Mathadon could you have a look at it and see if it's because of the extra capacity in window has been removed? The difference for ZoneExample is due to the change of inclination of the walls. I also notice that the 'EnergyConservationValidation' model gives an error during the simulation. So I've probably made a mistake with the energy conservation equations...

**Comment by Mathadon** [comment]
working on it :)

**Comment by Mathadon** [comment]
this can be merged after #446 and #448

**Comment by Mathadon** [comment]
replaced by #453

**Pull request closed without merging**
