### PR TITLE
Issue227 heat pump names

### PR DESCRIPTION
**Pull request by Mathadon**
This is for #227 and #243 
Updated heat pump connection names
COP is now calculated based on outlet temperature of the condensor instead of the inlet temperature
changed some unit tests and examples
fixed some bugs in examples

updated reference results

### CODE REVIEW

**Comment by Mathadon** [comment]
This is ready to merge

**Comment by damienpicard** [comment]
What is the reason for using 'IDEAS.Fluid.Interfaces.PartialFourPortInterface'  and not 'IDEAS.Fluid.Interfaces.FourPortHeatMassExchanger'? You add all the parameters in the partial heat pump model while the only differnce is the temperature sensor (which could be hard coded).

I would also get rid of all the *brine* and *fluid* naming and replace it by *1* and *2*.

**Comment by damienpicard** [comment]
After solve my first question, we can merge it.

**Comment by Mathadon** [comment]
Everything looks fine to me now!

**Comment by Mathadon** [comment]
Unit tests are ok.

**Pull request merged**
