### PR TITLE
Issue796 boundary

### PR DESCRIPTION
**Pull request by Mathadon**
for #796 

This pull request revises the way we compute air infiltration. Four replaceable options now exist. Two of them are 'air tight' and two of them are 'air open'. Both these options are idealisations of reality corresponding to infinite or zero pressure drop towards the environment. For each of these two options I made a version with and without the n50 air infiltration model, which has thus been removed from the `ZoneAirModel` series. By default the n50 value can now also be defined at the `SimInfoManager` level, which makes it easier to change the n50 value for all zones at once. 

This implementation is mostly reverse compatible, although some issues may arise when using specific options. The `Thermal` ZoneAirModel has been removed since it is incompatible with the new models and it serves no real use? 

@damienpicard @GlennReynders this is quite an important change that will be hard to change afterwards without messing up everybody's models. Perhaps we should sit together such that I can explain the changes in a bit more detail?

### CODE REVIEW

**Comment by Mathadon** [comment]
todo 
 - [ ] add assert that checks whether both fluid ports are connected for air open configuration. To avoid wrong use of the model.
 - [ ] interzonal air flow to advanced tab
 - [ ] remove n50 parameter from SimInfoManager and revise detailed interzonal air flow model accordingly
 - [ ] think about naming like `NoPressureDrop` `Fixed(Zone)Pressure` instead of `AirOpen`

**Comment by damienpicard** [comment]
Careful that `IDEAS.Buildings.Components.ZoneAirModels.Thermal` is used in LIDEAS. We should move LIDEAS to IDEAS and include its examples in the unit tests suit.

**Comment by Mathadon** [comment]
I think the fluid model will produce the same result if a dry air model is used.

**Comment by Mathadon** [comment]
@damienpicard if you can make a pull request for merging LIDEAS? then I will review it and we can we can wait with merging this pull request such that we don't break anything.

**Comment by damienpicard** [comment]
@Mathadon ok, i'll make a pull request

**Comment by Mathadon** [comment]
@GlennReynders do you have an idea how to rename `AirOpen` and/or `AirTight`?

**Comment by Mathadon** [comment]
@damienpicard I have discussed this already with @GlennReynders. If we can sit together some time then this can be merged.

**Comment by GlennReynders** [comment]
@Mathadon instead of `AirOpen` I'd prefer `FixedPressure`, but then there is no good alternative for `AirTight`. 
Maybe `AirTight` would not need a specific name, as this seems to be the general case? So then `FixedPressure` is an alternative for the general version.

**Comment by Mathadon** [comment]
@GlennReynders sounds good to me! I'll check with @damienpicard

**Comment by damienpicard** [comment]
this can be merged after resolving the conflict and travis.

**Pull request merged**
