### PR TITLE
added buildingshade component

### PR DESCRIPTION
**Pull request by Mathadon**
Added optional second shade component in window.

This is for #342 .

Please check if you agree with the naming.

### CODE REVIEW

**Comment by Mathadon** [comment]
Verified and added new reference result

**Comment by rubenbaetens** [comment]
Mm, this looks a weird way of implementing obstructing objects, i.e. not very generic. Usually this is done by defining "a horizon" which is then included in the calculation of the incident solar radiation.

**Comment by Mathadon** [comment]
I'm up for a discussion, but this works for me :)

**Comment by Mathadon** [comment]
I need to document this component and add a figure.

**Comment by Mathadon** [comment]
See other pull request.

**Pull request closed without merging**
