### PR TITLE
Project itz

### PR DESCRIPTION
**Pull request by Mathadon**
@jelgerjansen these are the changes that I have announced. A summary:
     - refactored partialsurface such that it includes CrackOrOperableDoor
     - CrackOrOperableDoor implements both a regular orifice equation and a door
     - depending on the settings of interzonalairflow the former or the latter is used
     - both in a window and an internal wall the operable door can be used to increase the air flow rate
     - control inputs are added for this
     - added an optional control signal for a trickle vent in a window
     - added unit tests for the above
     - the amount of diffuse/direct light entering the zone is reduced/increased depending on the window opening control signal
     - an input for adding custom water vapor to the zone model ahs been added
     - an input for adding custom co2 to the zone model ahs been added
     - an output for the relative humidity has been added to the zone model
     - the reflection coefficient implementation in the window has been improved
     - the bridge type implementation has been refactored such that the user no longer must provide the bridge type length to get a reasonable estimate of the bridge
     - n50 value computed based on total window surface area instead of just the glass
     - revised direct solar absorption implementation of the screen

I have added some new unit tests for which I could not generate reference results. Can you help out with this?

### CODE REVIEW

**Comment by Mathadon** [comment]
when reviewing this it could help to first merge #1322 since those changes are included here too.

**Comment by Mathadon** [comment]
Note that I have revised the screen model equations since the new implementation seems more correct to me. I.e. the non-absorbed fraction of direct solar radiation is not converted into diffuse solar irradiation but it stays direct instead.

**Comment by jelgerjansen** [comment]
@Mathadon can I/you merge the latest master branch into this pull request? Or is there a specific reason why not?
If not I cannot generate new reference results and compare them to the latest reference results (both were added to the main branch in PR #1319)

**Comment by Mathadon** [comment]
done, but we'd better merge the stack effect branch first such that we can see the diff compared to that branch once it's finalised.

**Comment by Mathadon** [comment]
@jelgerjansen it seems that the merge of the master branch breaks the code

**Comment by jelgerjansen** [comment]
The changes of this PR are included in https://github.com/open-ideas/IDEAS/pull/1327. Further development of project itz fixes will take place in that PR.

**Pull request closed without merging**
