### PR TITLE
Merge IBPSA into IDEAS

### PR DESCRIPTION
**Pull request by lucasverleyen**
I have merged the latest IPBSA master branch of today (https://github.com/ibpsa/modelica-ibpsa/commit/8ed71caee72b911a1d9b5a76e6cb7ed809875e1e) into this branch.

### CODE REVIEW

**Comment by lucasverleyen** [comment]
I'll list here some issues that popped up while updating the reference results
- IDEAS.Airflow.AHU is an IDEAS only package: I have changed the use_inputFilter to use_strokeTime or use_riseTime for the pumps and valves according to the new implementation in IBPSA.
- IDEAS.Airflow.AHU is an IDEAS only package: the pump performance data parameters do not match the IBPSA generic data format anymore. still needs to be updated...

**Comment by lucasverleyen** [comment]
@jelgerjansen I have reverted all reference results updates to their original state. I'll start regenerating the changed reference results systematically to have a clear overview of the changes.

**Comment by lucasverleyen** [comment]
@jelgerjansen, a few hints as to why we have some very small deviations in the new reference results:
- https://github.com/ibpsa/modelica-ibpsa/issues/1716: this has led to minor changes in the reference results in the Buildings library (https://github.com/lbl-srg/modelica-buildings/pull/3374/files). We also use these models in our SimInfoManager and this might explain the small 
- there have been made changes in the PartialMixingVolume, but should not give deviations (https://github.com/ibpsa/modelica-ibpsa/issues/1650)
- MassFlowSource_WeatherData has also been modified, but is not used as far as I can see...

**Comment by jelgerjansen** [comment]
@lucasverleyen I would think that the 'Diffuse radiation error' only affects models with a simulation end time surpassing one year, which is not the case for the unit test models, right?

**Comment by lucasverleyen** [comment]
@jelgerjansen that sounds indeed logical. However, I found reference results that were changed slightly, even if they took less than 1 year. e.g. https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Resources/Scripts/Dymola/Controls/Predictors/Examples/BESTEST.mos. with reference results in pull request https://github.com/lbl-srg/modelica-buildings/pull/3374/files

**Comment by jelgerjansen** [comment]
The small changes in reference results for IDEAS models might be due to several reasons:

- Used version of BuildingsPy and its dependencies (e.g. pyfunnel)
- [This IBPSA PR](https://github.com/ibpsa/modelica-ibpsa/pull/1722) might have a minor effect on the event handling for models using the weather data reader

**Comment by jelgerjansen** [comment]
I added a couple of missing unit tests, more specifically:

- IDEAS.Electrical
- IDEAS.Fluid.FMI
- IDEAS.Fluid.Humidifiers
- IDEAS.Fluid.Production
- IDEAS.Fluid.SolarCollectors

Some of these unit test models show changes in translation statistics and minor differences in reference results. The former is due to the used Dymola version (currently 2022x for IDEAS, but 2024x for IBPSA), the latter probably as well (or the used version of BuildingsPy and dependencies, as discussed above).

**Review by jelgerjansen — APPROVED** [review]

**Pull request merged**
