### PR TITLE
added air cavity model and integrated this

### PR DESCRIPTION
**Pull request by Mathadon**
For #211 

I have added correlations for horizontal and vertical air layers. They are evaluated into a linear resistance. This way the models do not become more complex. The model is used in the window model and the wall model.

@GlennReynders can you review the implementation?

### CODE REVIEW

**Comment by rubenbaetens** [comment]
I once implemented correlations as can be found (but commented) in `IDEAS.Buildings.Components.BaseClasses.MonoLayerLucent` but found no impact as the Nusselt numbers seem to be constant throughout the simulation. 

Though, this is a bit in contrast to the big difference in one of your simulations with a *large* cavity in the window...

**Comment by Mathadon** [comment]
It depends on the cavity size of course :) what large cavity do you mean?

**Comment by rubenbaetens** [comment]
The once you mention here as reason why differences occur in your unittests: https://github.com/open-ideas/IDEAS/commit/32a3a1b14e2f4b44691622b6fe6460f88357a848

**Comment by Mathadon** [comment]
screen shot 2016-01-06 at 18 35 58

I checked it again. The compute Nu value is 1.56. When I override it to 1 then indeed a large temperature difference occurs. Do you think this is a bug? To me this just seems to logical consequence of the increased accuracy?

**Comment by rubenbaetens** [comment]
A high Nu-value of 1.5 corresponds to a cavity of 2 to 3 cm;
does this corresponds with the case you're simulating ?

**Comment by Mathadon** [comment]
I think the cavity was 15 mm in this case. However the default value for dT_nominal = 10K, which may need to be lower..?

**Comment by rubenbaetens** [comment]
`dT_nominal = 10K` is on average correct, but `dT` ranges in reality from 0 K tot 20 K ... linearisation based on dT_nominal *might* cause a ratehr large error here.

**Comment by Mathadon** [comment]
That's true, but it's better than what we have now, no?

**Pull request merged**
