### PR TITLE
Issue515 solar gains

### LINKED ISSUE #515: Solar gains model
Currently beam solar gains are redistributed over alle surfaces based on the emissivity-weighted areas of the surfaces. This model is fairly simple and should probably be improved. A first improvement would probably be to assume that all beam irradiation falls onto the floor and to determine which surface is the floor based on the inclination angle etc.

Any other suggestions?

### PR DESCRIPTION
**Pull request by Mathadon**
This is a proposal to close #515

### CODE REVIEW

**Comment by Mathadon** [comment]
Bestest:
Before - after (600):
[case600.pdf](https://github.com/open-ideas/IDEAS/files/422603/case600.pdf)[case600.pdf](https://github.com/open-ideas/IDEAS/files/422605/case600.pdf)

**Comment by Mathadon** [comment]
@GlennReynders this is again ready to be merged.

**Comment by rubenbaetens** [comment]
@Mathadon Could you add somewhere a description of how beam radiation is treated here ?

**Comment by Mathadon** [comment]
done

**Comment by rubenbaetens** [comment]
OK, @GlennReynders, could you have a look at it ? You mentioned it yesterday too, that you tried once the same. Would this be a good middle-way between a non-geometric approachand a full-geometric approach ?

**Comment by GlennReynders** [comment]
Especially in summer when solar gains are highest and for south oriented rooms, this approximation should perform better than the old version, so indeed good middle-way.

**Comment by GlennReynders** [comment]
@Mathadon I'm ok with the changes. Could you have a quick look at conflicts, then I'll merge.

**Comment by Mathadon** [comment]
There is no such thing as having a quick look at conflicts..

**Comment by Mathadon** [comment]
done

**Pull request merged**
