### PR TITLE
Issue771 fan coilv3

### PR DESCRIPTION
**Pull request by Mathadon**
@icupeiro can you verify these changes?

There were still a few bugs in the implementation so the results changed a lot. The total heat flow rate is now ok but the sensible heat flow rate is too large (latent too small). To be looked into further. If you have suggestions for improvements, would be welcome!

### CODE REVIEW

**Comment by icupeiro** [comment]
@Mathadon not sure about the computation of the cpwet (saturation conditions)
If you run the model IDEAS.Fluid.HeatExchangers.Validation.NTUWetInDryRegime (you have to establish initial conditions, otherwise you get an error due to division by zero) you can see that the cp does a huge peak at the moment the inlet temperatures of water and air cross. Could this cause some problems?
I am in favour of compute the Cp for full dry and wet conditions, and apply a fraction factor in partial conditions. However, this could introduce one or two algebraic loops.
- Dry conditions: calculation as it is
- Wet conditions: calculation as what I proposed first (this only by itself would cause the jump)
- Partially conditions: this should compute some sort of ramp between the full dry and full wet conditions
The conditions would be determined by the surface temperature of the H-Ex, which can be computed as a variable according to Braun's correlations
1. If the surface temperature at the outlet is less than the inlet air dew point, then assume full wet (see calculation)
image
2. If the surface temperature at the inlet is greater than the inlet air dew point, then the coil is in partial conditions
However, this looks tricky to implement since it is a step-by-step approach... not sure what to do here.

**Comment by icupeiro** [comment]
@Mathadon based on feedback from IBPSA meeting these days I'd suggest the following To-Do's:

- Implementation of the Wet NTU model: first priority, perhaps in a different issue/merge?
- To be checked: cross-validation of cooling coil; Perhaps we can choose a different "transition" temperature?

- Fan coil: use 4 port interface, so we can pass the change in water content to the zone
- Extend the fan record and validate those with the manufacturer data
- Add two-way valve and check control with manufacturer e.g. JAGA
- Validate model with data from other manufacturer

Do I miss something?

**Comment by Mathadon** [comment]
I figured out what's wrong with the cross-validation: the UA value computations are not consistent, also UA_nominal should take into account condensation.

First step is to create pull request for condensing HEX. I'll work on something.

**Comment by Mathadon** [comment]
discussion continued in https://github.com/ibpsa/modelica-ibpsa/issues/1109 and

**Pull request closed without merging**
