### PR TITLE
add unit test script for python 3.

### PR DESCRIPTION
**Pull request by damienpicard**
This solves #706 . Notice that you need to pull the lastest version of `BuildingsPy`.

I notice that the unit test implementation I used is pretty different from https://github.com/open-ideas/IDEAS/blob/master/IDEAS/RunUnitTests.py. Does anybody use the current script from `IDEAS`?

### CODE REVIEW

**Comment by Mathadon** [comment]
I use it

**Comment by damienpicard** [comment]
Do you know where all the functions of my script are coming from and if they have any added values?

**Comment by Mathadon** [comment]
no, where did you get the script? :p I'm sure it can be made shorter.

**Comment by Mathadon** [comment]
@damienpicard we should probably have one script that works for all of us. I need to take some time to figure out how I can get this working for me.

**Comment by Mathadon** [comment]
@damienpicard could the existing script not be adjusted such that it is compatible with both python2.7 and python3?

**Comment by damienpicard** [comment]
The default IDEAS `RunUnitTest.py` works for python 3.4

**Pull request closed without merging**
