### PR TITLE
fixed some issues in heating system and ventilation system

### PR DESCRIPTION
**Pull request by Mathadon**
Hey Christina, can you verify these fixes?
Then we can have a look how best to merge this to master.

### CODE REVIEW

**Comment by cprotopa** [comment]
@Mathadon , I've checked the commit (the text changes) and it seems to me that you changed exactly the problems I had spotted.
I supposed you've checked the models and they work. Cause I don't really know what is a fast way to check the models myself? Pull from the specific branch? Or download the branch? How do you normally do it? 
Thanks a lot, btw.

**Comment by Mathadon** [comment]
I just 'check'ed the models and that did not produce any errors. I.e. I did not run any simulations.

I guess this change needs to be added to the master as well?

**Comment by cprotopa** [comment]
I can only imagine problems can show up because of "Medium stuff" when connecting to the Building interface! :) 
Yes, it should be in the master branch, because that's what we'll use for the crashcourse.

**Comment by Mathadon** [comment]
I added it on master!

**Pull request merged**
