### PR TITLE
Add button to select the weather file graphically in the SimInfoManager.

### PR DESCRIPTION
**Pull request by jotaborrajo**
Just to select the weather file easily.

image

### CODE REVIEW

**Comment by Mathadon** [comment]
@jotaborrajo thanks for this PR! Can you add a note in the revision history?

**Comment by jotaborrajo** [comment]
@Mathadon I think I did it. I am not yet familiar with git.

**Comment by Mathadon** [comment]
you did, just not in the correct format, but I'll change that!

**Comment by Mathadon** [comment]
closing to run unit tests

**Pull request closed without merging**
