### PR TITLE
Issue258 temperature security

### PR DESCRIPTION
**Pull request by damienpicard**
This pull request solves #258 . I did not use the partial class for the production source, as the model structure is not yet sure.

### CODE REVIEW

**Comment by damienpicard** [comment]
unit tests are updated (I changed the example: `heatPump_WaterWater' and the other unit tests gave the same results).

**Comment by damienpicard** [comment]
Unit tests are for me OK.

**Comment by Mathadon** [comment]
@damienpicard I made some small changes. Can you merge the pull request if you agree?

**Comment by Mathadon** [comment]
Unit tests were ok as well.

**Comment by Mathadon** [comment]
@damienpicard can you check this ?:)

**Pull request merged**
