### PR TITLE
Stack effect airflow

### PR DESCRIPTION
**Pull request by kldjonge**
New pull request following https://github.com/open-ideas/IDEAS/pull/1296

### CODE REVIEW

**Comment by kldjonge** [comment]
New pull request following https://github.com/open-ideas/IDEAS/pull/1296

**Comment by kldjonge** [comment]
@Mathadon, I tried another implementation using Modelica.Fluid.Fittings.MultiPort

`
This model is useful if multiple connections shall be made to a port of a volume model exposing a state, like a pipe with ModelStructure av_vb. The mixing is shifted into the volume connected to port_a and the result is propagated back to each ports_b. 
If multiple connections were directly made to the volume, then ideal mixing would take place in the connection set, outside the volume. This is normally not intended.
`

 I thought this might solve it as it didn't ideally mix the large openings with the small cracks anymore but it didn't help.
Still the PPD12 model is singular when the two-port version is implemented.

**Comment by Mathadon** [comment]
@kldjonge I'm not sure whether the MultiPort is a good idea. I'd have to check whether algebraic loops get formed without it. In theory but mass flow rates that are in parallel should have the same flow direction, so the mixing equations should not cause a big problem. But it's true that having a multiport would be more correct.. However, I think it's hard to maintain and it may freak out some compilers. 

Do you really need this or was it just an attempt to solve the bug and can we close this?

**Comment by kldjonge** [comment]
The new pull request is just because my branch wasn't linked to a pull-request anymore. So their are more commits then only the one with the multi-port. I just left it in because I didn't think it would do any harm and would be helpful when we would ever need more ports.

"In theory but mass flow rates that are in parallel should have the same flow direction", is this still always the case when stack-effect columns are introduced? E.g. an opening at ceiling height can be above the neutral plane whereas the nodes for can both be under.

But if it actually does mess things up, I can revert the implementation offcourse.

**Review by kldjonge — COMMENTED** [review]
Commit describtion is wrong here, I reverted the multiport implementation not the tricklevent implementation

**Comment by Mathadon** [comment]
@kldjonge thanks for the revert! Perhaps it's indeed possible that mixing occurs due to the stack effect implementation. But even then, I'd like to not add a vector of ports for now. I'll try to have a look at it in my review.

I understand correctly that you're still getting a singular model? Even for some single-zone examples? I'm thinking of we how we could best debug that.. It doesn't sound easy :p

**Comment by kldjonge** [comment]
It's only in multizone models with hasCavity. So only when the dooOpe model in the internal wall becomes active.

**Comment by Mathadon** [comment]
Aha, then it should be easier to pinpoint. I'll try to make some time for a review this week.

**Pull request merged**
