### PR TITLE
New implementation for InteriorConvection

### PR DESCRIPTION
**Pull request by Mathadon**
for #283 

@rubenbaetens can you have a look at the new implementation? I'm running unit tests right now. 

I added an option for creating a state for the convective heat transfer coefficient but this does not seem to have a  large impact on the simulation speed so I put it to false by default.

Also is it necessary to make a distinction with InteriorConvectionWindow?

### CODE REVIEW

**Comment by rubenbaetens** [comment]
@Mathadon don't focus on the differences in the unit tests, it's logic, it would even be strange otherwise, we changed physics, and it will have its impact especially for the 600-cases. As the unittests are the BESTESTs, we maybe better 'fix' the hcon there.

**Comment by rubenbaetens** [comment]
@Mathadon in caqe that making hco na state doesn't have any 'accountable' difference, i suggest we leave out this option to avoid confusion (?).

**Comment by rubenbaetens** [comment]
@Mathadon something went wrong in your `if isCeiling or isFloor then ... else ...` statement i think, as your `else`-option is the old `fixed=true` option. I'll correct and commit, you could rerun the unittest but i think it has little value.

**Comment by Mathadon** [comment]
Well I figured that the old correlation still applied to vertical walls, which are not treated right now by the if/else clause. So in that case it defaults to the old correlation. 
However I do agree that having a (more) correct correlation for walls would be nice.

**Comment by Mathadon** [comment]
I'll rerun unit tests and accept the results just to have them updated then.

I do think the option may be necessary for larger systems, when connecting ~20 components to a zone, since this leads to relatively large non-linear systems. I'll try to figure this out using one of my models.

**Comment by Mathadon** [comment]
@rubenbaetens can you verify my last commit?

**Comment by rubenbaetens** [comment]
@Mathadon your last commit seems ok, i'm only wondering how to find the nominal value for `dT_nominal` as `3 K` seems somehow too much.

**Comment by Mathadon** [comment]
I’m not sure what would be a good value. Feel free to change it!

**Comment by rubenbaetens** [comment]
Closing was an accident-de-parcours, suddenly `develop` wwas gone, causing the pull requests to close for i-don't-know-which-reason.

**Comment by Mathadon** [comment]
@rubenbaetens can you have another look at this?

**Comment by Mathadon** [comment]
Unit test differences are quite large, which is logical since previously the heat convection coefficients were assumed to be orientation-independent. Do we need to go over them or should I just accept them?

**Comment by rubenbaetens** [comment]
Well, you're no longer testing the same. But these are BESTEST models and i
would maybe prefer to have them back the old way in those tests ...

**Comment by Mathadon** [comment]
You mean with a constant value of ```h=3``` for all surfaces?

Maybe it would be best to compare which of the two options best matches the bestest results? Do you have the results from BesTest somewhere?, then I can have a look.

**Comment by Mathadon** [comment]
@rubenbaetens ?

**Comment by Mathadon** [comment]
@rubenbaetens ..?

**Comment by Mathadon** [comment]
The pull request has been updated. Unit test differences are quite large:
screen shot 2015-07-06 at 11 54 20
screen shot 2015-07-06 at 11 54 46
screen shot 2015-06-30 at 15 45 18

**Comment by rubenbaetens** [comment]
Mm, this difference is indeed big but looks contradictory: Teh temeprature drops are almost doubled, while the required heating power ... decreases ?

**Comment by Mathadon** [comment]
I think it's logical: h is in general lower, which means that the walls can cool down further while having the same thermal losses. Ie. the radiative temperature drops, but that does not mean the thermal power should rise.

**Comment by Mathadon** [comment]
I'm changing dT_nominal to be negative by default since buildings are more often in heating mode. I'm rerunning unit tests.

**Comment by Mathadon** [comment]
Deviations are still quite large. 
When not linearising the results are quite similar. 
I guess h was just too large in the old implementation?

**Comment by rubenbaetens** [comment]
Well, yes, the correlation equations a.dT^b are indeed usually lower than the fixed-value h's ...

**Comment by Mathadon** [comment]
So then this can be merged?

**Comment by rubenbaetens** [comment]
Should i also delete the branch, or you want to keep it for a while ?

**Pull request merged**
