### PR TITLE
sha logging functionality for #940

### LINKED ISSUE #940: utility for storing sha of a model
When developing models in a separate library from IDEAS, it can be useful to save the IDEAS sha in that library to properly track its dependencies. I propose to develop a block that automates this.

### PR DESCRIPTION
**Pull request by Mathadon**
this closes #940

### CODE REVIEW

**Comment by Mathadon** [comment]
@damienpicard should I include an example?

**Comment by Mathadon** [comment]
@damienpicard this is ready to be merged

**Comment by damienpicard** [comment]
@Mathadon When I try to compile the GitShaLogger model I get the following error:

```
Compiling and linking the model (Visual C++). 
 
64-bit mode activated. 
dsmodel.c
c:\program files (x86)\dymola 2017\source\dsutil.h(238) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
C:/Program Files (x86)/Dymola 2017\source\matrixop.h(186) : warning C4267: 'function' : conversion from 'size_t' to 'SizeType', possible loss of data
C:/Program Files (x86)/Dymola 2017\source\matrixop.h(1001) : warning C4267: 'function' : conversion from 'size_t' to 'SizeType', possible loss of data
C:/Users/u0085306/Documents/work/modelica/IDEAS/IDEAS/Resources/C-Sources\tagcommit.c(20) : warning C4013: 'popen' undefined; assuming extern returning int
C:/Users/u0085306/Documents/work/modelica/IDEAS/IDEAS/Resources/C-Sources\tagcommit.c(20) : warning C4047: '=' : 'FILE *' differs in levels of indirection from 'int'
C:/Users/u0085306/Documents/work/modelica/IDEAS/IDEAS/Resources/C-Sources\tagcommit.c(27) : warning C4013: 'pclose' undefined; assuming extern returning int
C:/Program Files (x86)/Dymola 2017\source\ModelicaStrings.c(94) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
C:/Program Files (x86)/Dymola 2017\source\ModelicaStrings.c(127) : warning C4267: 'return' : conversion from 'size_t' to 'int', possible loss of data
C:/Program Files (x86)/Dymola 2017\source\ModelicaStrings.c(225) : warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data
dsmodel.c(147) : warning C4267: 'function' : conversion from 'size_t' to 'int', possible loss of data
   Creating library dymosim.lib and object dymosim.exp
dsmodel.obj : error LNK2019: unresolved external symbol popen referenced in function getCommit
dsmodel.obj : error LNK2019: unresolved external symbol pclose referenced in function getCommit
dymosim.exe : fatal error LNK1120: 2 unresolved externals
 
Error generating Dymosim.
```

Have you try your code on  your windows virtual machine?

**Comment by damienpicard** [comment]
The new version works. This can be merged.

**Pull request merged**
