### PR TITLE
894 merged

### PR DESCRIPTION
**Pull request by Mathadon**
This merges IBPSA changes, updates to MSL 4.0.0 and version bumps to IDEAS 3.0.

### CODE REVIEW

**Comment by Mathadon** [comment]
@kldjonge I hope to merge this in one of the coming days

**Comment by kldjonge** [comment]
@Mathadon, thanks for keeping me updated. I will wait for after the merge to work on https://github.com/open-ideas/IDEAS/pull/1246 then, so that I can update the branch to MSL 4.0 as well.

**Comment by Mathadon** [comment]
@kldjonge this has been merged! the official release will follow soon

**Comment by kldjonge** [comment]
@Mathadon, thanks for the update! Seems like it was quite a bit of work. Very happy to see the IBPSA changes and IDEAS airflow implementation available together.

**Pull request merged**
