### PR TITLE
Issue1049 tutorialv2

### PR DESCRIPTION
**Pull request by Mathadon**
more models, still to be finished
for #1049

### CODE REVIEW

**Comment by Mathadon** [comment]
@damienpicard this is ready for review

**Comment by damienpicard** [comment]
@Mathadon it looks very good. Just some questions/comments

- Example 6 uses the convective temperature for thermostatic temperature. Why not using the operative temperature of the zone? 
- Example 6 uses the same reference pressure at each sides of the heat pump. I would use two different ones. In reality, you also need to put two expansion valves.
- Example 7:  I would use a TemperatureTwoPort sensor instead of using the heatPort of pump. This is more physical but also, it teaches the student to use this twoPort sensor instead of onePort sensor.
- The reason why the model is so slow is that the heat pump is turned on and off every 100s. This is not realistic. I would down side the heat pump, and possibly add a mixing volume (buffer tank). However, this is an interesting phenomenon to show to the student: a physical reason which explains why your simulation is slow.

**Comment by Mathadon** [comment]
- Using TSensor
- Separate boundary for reference pressure
- Using TemperatureTwoPort
 -Using stratified storage tank since mixing volume is not in line with modeling philosophy of this exercise.

**Comment by damienpicard** [comment]
This is ready to be merged.

**Pull request merged**
