### PR TITLE
Update master branch

### PR DESCRIPTION
**Pull request by Mathadon**
@rubenbaetens @damienpicard @GlennReynders 

I propose to update the master branch and to then communicate this beta release to our respective departments. They can then try this version and flag any problems that may arise when using the conversion script etc.

If everything turns out fine we can tag ideas 1.0.

In the future I propose to no longer use the develop branch, but to use the master branch for continuous development since this is also how Annex60 and Buildings work. We can then refer to version 1.0 for the 'stable' version.

Please approve asap :)

### CODE REVIEW

**Comment by damienpicard** [comment]
@Mathadon , before communicating it to our department, I would check that our models ( @GlennReynders , @rubenbaetens and @Mathadon ) are working with this master branch. Then, we can ask the other users (with a deadline for reporting problems) and finally we can release tag1.0.

**Comment by damienpicard** [comment]
Actually, I like having a developing branch and a master branch. Master branch can be used to update minor changes while develop branch can be used to even have non-backward compatible changes. Tags can be used for official releases.

What do you thing?

**Comment by damienpicard** [comment]
Alright, all my models work again with the new IDEAS. I just had to remove the `insulationTickness` and to adapt the `ConstructionType` records accordingly. For one model, I also had to use `simVieFac` in order to avoid convergence problems.

**Comment by Mathadon** [comment]
We could Apply hotfixes on the master branch but we never did this in the past and i dont think we will in the future. So I'd rather follow the Annex60 system.

@glennreynders can this be merged?

**Comment by GlennReynders** [comment]
I had to manually run conversion script first, but that worked. Only the zone-parameter `corrCV` was bit changed by the conversion script. This should become `mSensFac`. Like @damienpicard, I had to remove `insulationType` and `insulationThickness` as they are no longer used.

**Comment by Mathadon** [comment]
this can be merged after #667 and #668

**Pull request merged**
