### PR TITLE
bugfix for borefield

### LINKED ISSUE #699: bug in borefield
- The  `beta` variable of `singleUTubeResistances` is used before being calculated in the algorithm section. It should be moved up.

- `TWall` seems not to be connected to all borehole element when boreholes in series are used.

I'll propose a pull request.

### PR DESCRIPTION
**Pull request by damienpicard**
This fixes #699 : in singleUTubeResistances.mo (order of equation in algorithm section) and in PartialSingleBoreholeSerie.mo (TWall was not correctly connected when boreholes in series are used).

### CODE REVIEW

**Comment by damienpicard** [comment]
@Mathadon I wanted to run the unit test (for the borefield model). However, on my new computer, I work with Python 3 and BuildingsPy uses Python 2.7...

I've then tried to run the unit tests in Linux but I get the following error:
```
dap@ubuntu:~/Documents/modelica/IDEAS/IDEAS$ python RunUnitTestsDaP.py
Regression tests are only run for the following package:
  IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield
Using 2 of 2 processors to run unit tests.
Traceback (most recent call last):
  File "RunUnitTestsDaP.py", line 90, in <module>
    _runUnitTests()
  File "RunUnitTestsDaP.py", line 46, in _runUnitTests
    retVal = ut.run()
  File "/usr/local/lib/python2.7/dist-packages/buildingspy-1.6.0-py2.7.egg/buildingspy/development/regressiontest.py", line 2217, in run
    self.printNumberOfClasses()
  File "/usr/local/lib/python2.7/dist-packages/buildingspy-1.6.0-py2.7.egg/buildingspy/development/regressiontest.py", line 1771, in printNumberOfClasses
    iMod = self._checkKey("model", filFulNam, iMod)
  File "/usr/local/lib/python2.7/dist-packages/buildingspy-1.6.0-py2.7.egg/buildingspy/development/regressiontest.py", line 421, in _checkKey
    filTex=filObj.readline()
  File "/usr/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/usr/lib/python2.7/encodings/utf_8_sig.py", line 66, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb4 in position 2210: invalid start byte
```

I don't think I'll have the time to look at that issue before June. Could you maybe run the unit tests for this pull request? (Only the models in `IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield`). I expect some minor differences as the borehole resistance and the borehole wall temperature for boreholes in series will change with the bugfixes.

Thx!

**Comment by Mathadon** [comment]
@damienpicard buildingspy should work with python 3.0 but you probably need to update your version.

I'll run unit tests in the meantime!

**Comment by Mathadon** [comment]
trouble in paradise!

```
The following error was detected at time: 0
Maximum number of iterations exceeded. Check the borehole geometry.
  The tubes may be too close to the borehole wall.
  Input to the function 
  IDEAS.Fluid.HeatExchangers.Boreholes.BaseClasses.singleUTubeResistances
  is
           hSeg = 4 m
           rBor = 0.075 m
           rTub = 0.025 m
           eTub = 0.0023 m
           kSoi = 2.19 W/m/K
           kFil = 2.32 W/m/K
           kTub = 0.38 W/m/K
           i = 11
  Computed x    = 0.269029 K/W
           Rgb  = 0.0207026 K/W
           Rgg  = -0.00094376 K/W
The stack of functions is:
IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield.BaseClasses.BoreHoles.BaseClasses.singleUTubeResistances
IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield.BaseClasses.BoreHoles.BaseClasses.singleUTubeResistances(borHolSer.borHol[1].borHolSeg[1].intHEX.gen.use_Rb, borHolSer.borHol[1].borHolSeg[1].intHEX.gen.Rb, 4.0, borHolSer.borHol[1].borHolSeg[1].intHEX.gen.rBor, borHolSer.borHol[1].borHolSeg[1].intHEX.gen.rTub, borHolSer.borHol[1].borHolSeg[1].intHEX.gen.eTub, borHolSer.borHol[1].borHolS...
Error: Failed to start model.
```

**Comment by Mathadon** [comment]
I suppose Rgg should not be negative?

**Comment by damienpicard** [comment]
As explained in Bauer 2011 paper, `Rgg` can be negative as the total resistance remains positive.
I've looked at the models and I noticed the following

- `TrtValidationMultipleBoreholeUTube` uses `GeneralTrtUTube` which set the parameters `rBor=0.075, rTub = 0.025 and xC=0.075/3.7=0.02`. `xC` is the distance from the center of the borehole to the center of the pipe. It is not physical that `xC < rTub`. Once `xC=0.03` is used, the model run without problem. @Mathadon, I think you tuned the parameter xC to fit your data. Can you have a look at it again? Because with the new parameter value, the fit is less good.
- Similarly, several records in `IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield.Data.GeneralData` had non physical geometries. I've adapted them.

**Comment by damienpicard** [comment]
Unittest with current settings are running smoothly and the differences are small.

**Comment by Mathadon** [comment]
There should probably be min/max attributes for these parameters, or asserts, such that non-physical values are flagged to he user. Can you add this?
I'm using
```
    rBor=0.15/2,
    rTub=0.025/2,
    eTub=0.0029,
    xC=rBor/2.5,
```
in my own model, which uses `MultipleBoreHoles2UTube` so that may explain the different results.

I'll update the validation model to `MultipleBoreHoles2UTube` and add a comparison between `MultipleBoreHoles2UTube` and `MultipleBoreHolesUTube`.

**Comment by Mathadon** [comment]
For the comparison see #710 

I removed the validation for the single U tube bore field since it is based on data that does not corresponds to a single U tube bore field and therefore it's not a validation.

**Comment by damienpicard** [comment]
@Mathadon if you are fine with the assert, this can be merged.

**Comment by Mathadon** [comment]
unit tests were ok

**Pull request merged**
