### PR TITLE
split heat capacitor in Window model for #1092

### LINKED ISSUE #1092: split glazing and frame thermal mass
This is to avoid non-algebraic loops when merging  #1089 , which introduces a non-linear convection equation at the exterior while the current equation is linear.

### PR DESCRIPTION
**Pull request by Mathadon**
closes #1092

### CODE REVIEW

**Comment by Mathadon** [comment]
There is a bug in travis that has to be fixed before we can continue with this.

**Comment by Mathadon** [comment]
@damienpicard can you review this?

**Comment by damienpicard** [comment]
This looks good and it can be merged. My only concerns are:

- time constant is now half the one from before --> some of our model with Euler might experience difficulties
- i'm not sure whether all LIDEAS examples will still run as the number of states is now different (I don't now if everything is automatized in the models)

**Comment by Mathadon** [comment]
I indeed had to update the LIDEAS examples manually.

**Pull request merged**
