### PR TITLE
Issue187 moving average

### PR DESCRIPTION
**Pull request by damienpicard**
This address #187

### CODE REVIEW

**Comment by saroele** [comment]
@damienpicard What is the reason for the ``resetIntegral`` parameter? Can you make an example where it is illustrated?

Can you also create a unittest script for all the examples?

**Comment by saroele** [comment]
There is a missing base class from which you extent for the icon in the RunninMeantemperatureEN15251* models: 

``Simplified2ZonesOfficeBuilding.Control.Interfaces.SubController`` cannot be found.  Note that this may be due to merging Annex60 into this branch, which is the same as accepting this pull request on the Annex60 branch.  Maybe this baseclass moved?

**Comment by damienpicard** [comment]
@saroele the parameter <code>resetIntegral</code> is to avoid having number constantly growing (as it was the cost for iDelay and iStop, which are integral of temperatures). It can be illustrated by just plotted the protected variables iDelay and iStop and make sure that resetIntegral * period < simulationTime.

Thx for the noticing the missing interface. I solved it.

Finally I also added unittests.

@Mathadon I will merge this pull request as its models are not used by other models.

**Comment by Mathadon** [comment]
```
*** Error: MovingAverage.mos does not contain any plot command.
You need to add a plot command to include its
results in the regression tests.
*** Error: RunningMeanTemperatureEN15251.mos does not contain any plot command.
You need to add a plot command to include its
results in the regression tests.
```
Can you fix this @damienpicard ?

**Comment by damienpicard** [comment]
@Mathadon that's strange: the file is the following:
```
simulateModel("IDEAS.Controls.ControlHeating.Examples.RunningMeanTemperatureEN15251", stopTime=1e+007, numberOfIntervals=50000, method="dassl", resultFile="RunningMeanTemperatureEN15251");
plot({"runningMeanTemperature_discrete.TRm","runningMeanTemperatureEN15251_continuous.TRm"}, colors={{0,0,255},{255,0,0}});
```

calling the script simulate AND create the plot... !?

**Comment by damienpicard** [comment]
I noticed that if the dassl does not integrate the ambiant temperature well if the step size is too big. The discrete implementation should be used instead.

**Comment by Mathadon** [comment]
I think you should add: ```y=``` before the accolades?

**Pull request merged**
