### PR TITLE
Issue736 ntu h ex

### PR DESCRIPTION
**Pull request by icupeiro**
this solves #736

### CODE REVIEW

**Comment by Mathadon** [comment]
@icupeiro you seem to be mixing two pull requests? I.e. 	fe6125d is related to the fins?

**Comment by icupeiro** [comment]
ouch, it seems that I did not master git yet... =(

I left my laptop in the office, I will correct this tomorrow

**Comment by icupeiro** [comment]
@Mathadon changes should have been applied now?

**Comment by Mathadon** [comment]
The new file shows up in https://github.com/open-ideas/IDEAS/pull/737/files so that looks good :)
thanks!

**Pull request closed without merging**
