### PR TITLE
Stack effect airflow

### PR DESCRIPTION
**Pull request by kldjonge**
Another work-in-progress pull request so you can track my work more easily. I still had commits on my fork related to the contam-modelica airflow verification of PPD12 with o.a missing inputs.

The others (most) are mostly because I already merged the current master and the branch hasn't yet. Maybe we can merge the current master in the stackeffectairflow branch?

### CODE REVIEW

**Comment by Mathadon** [comment]
@kldjonge I deleted the density column because it's the only case where a density column was used in two-port configuration, which did not seem like a good idea. As far as I could tell anyway. :)

**Comment by Mathadon** [comment]
But I indeed noticed that a connection was missing :)

**Comment by kldjonge** [comment]
> 

Well, it actually is nececarry to keep it.  The general rule (when stack effect is included) is that each time that a zone is coupled to a flow element, a density must be used to account for the height difference between the center of the zone and the opening based on the temperature/density of the zone it connects to.

As an internal wall component connects to a zone a both sides, the  1 density column that is part of the default implementation is not sufficient.

**Comment by Mathadon** [comment]
@kldjonge sorry I made I typo in my post, should be:

"I deleted the density column because it's the only case where a density column was used in **_one_**-port configuration, which did not seem like a good idea. As far as I could tell anyway. :)"

Does it make sense then?

**Pull request closed without merging**
