### PR TITLE
Issue434 tapmodel

### PR DESCRIPTION
**Pull request by rubenbaetens**
Cleaned up version of tap models as denoted in #434. No changes in unittests.

### CODE REVIEW

**Comment by damienpicard** [comment]
@rubenbaetens the example does not run (flow reversal occurs). I updated the name and the .mos in upstream issue434_tapmodel. Can you look at the bug?

**Comment by rubenbaetens** [comment]
@damienpicard that's weird, i have a look at it, all worked fine on my laptop ...

**Comment by damienpicard** [comment]
Strange, because @Mathadon just told me that this example was also giving an error previously...

**Comment by rubenbaetens** [comment]
Actually the unittest doesn't work in the `develop`-branch either.

**Comment by Mathadon** [comment]
See #450

**Pull request closed without merging**
