### PR TITLE
addded vector fluid port to zone for #1029

### LINKED ISSUE #1029: array of ports in zone model
Current zone implementation has two air ports intentionally, one for the inlet air and one for the outlet air
The problem comes when the direction of the stream is unknown. It can happen, for instance, that in the same port there are inlet and outlet streams, and in this case there is a possibility that the air streams do not exchange mass/energy with the zone air volume.

A proposed solution is to substitute these two ports by an array of ports, but this change would be non-backwards compatible. To be released in the next major version.

### PR DESCRIPTION
**Pull request by Mathadon**
closes #1029

### CODE REVIEW

**Comment by icupeiro** [comment]
I was gonna do this but I saw you already started... I had a look and it looks good, but let me know if you need further review

**Comment by Mathadon** [comment]
@icupeiro it would be helpful if you could check whether none of the IDEAS models are still using port_a or port_b. thx!

**Comment by icupeiro** [comment]
@Mathadon the model IDEAS.Buildings.Components.Examples.ZoneStatic is not updated, but a singularity is caused when I try to connect to the new port array. Is this expected?

On the other hand, the Infrax model works properly

**Comment by Mathadon** [comment]
@icupeiro check the Modelica code. Probably, a vector connection (`connect(zone.ports),...)`) is created instead of a scalar connection (`connect(zone.ports[1]),...)`).

**Comment by icupeiro** [comment]
yup. There was a problem on how modelica interpreted the port connections. I adapted it manually and it simulates. I pushed the changes

**Comment by icupeiro** [comment]
BTW the model should throw an error if nPorts is not coinciding with the actual number of connections

**Comment by Mathadon** [comment]
@icupeiro that's not needed since m_flow=0 is generated by default for unconnected ports, which is valid. This way we can also set `nPorts=2` by default such that users don't have to manually change it always.

**Comment by icupeiro** [comment]
@Mathadon my point is that if people adds more connections without realizing they should change nPorts parameter, those connections would have m_flow = 0 and therefore the model is gonna be wrong. In that sense, at least a warning pointing this issue for debugging purposes may be useful

**Comment by Mathadon** [comment]
Oh yeah, it makes sense to have `cardinality(ports[i]<=2)` (2 because there is an internal connection )

**Comment by Mathadon** [comment]
@damienpicard this is ready for review

**Pull request closed without merging**
