### PR TITLE
Issue998 scaled input occupancy

### LINKED ISSUE #998: scaled occupancy input block
Integrated scaling using zone surface area.

### PR DESCRIPTION
**Pull request by Mathadon**
this closes #998 
#995 should be merged first

### CODE REVIEW

**Comment by Mathadon** [comment]
@damienpicard can you review this?

**Comment by Mathadon** [comment]
@damienpicard can you review this?

**Comment by damienpicard** [comment]
This looks fine. However, shouldn't the conversion script be added somewhere?

**Comment by Mathadon** [comment]
I planned to collect the scripts at next release.

**Pull request merged**
