### PR TITLE
Issue45 boiler model

### PR DESCRIPTION
**Pull request by arnoutaertgeerts**
Pull request to develop (see https://github.com/open-ideas/IDEAS/pull/306#issuecomment-75975532)

### CODE REVIEW

**Comment by arnoutaertgeerts** [comment]
@damienpicard ? :)

**Comment by damienpicard** [comment]
The following changes need to be addressed:
. boiler and heat pump should extend 'TwoPortInterface' and 'ForPortInterface' respectively.
. heat losses to environment should be add for the evaporator too.
. sign of heat flow from the evaporator should have positive sign in heat source
. 2 different parameters should be used for the fluid mass in evaporator and condensor.
. On/off of heat source should have an effect also on non-modulation production
.  modulationSecurity should be added to the heatSource
. input QAsked of heatSource is sometimes used for temperature. This should be changed.
. Performance maps could be adapted to use SI units and so avoid errors.

Furthermore, some documentation could be added ;)

**Comment by damienpicard** [comment]
I'll  propose some changes.

**Comment by arnoutaertgeerts** [comment]
Already working on it :)

**Comment by damienpicard** [comment]
@arnoutaertgeerts @Mathadon According to me, this version of the boiler / heat pump is ripe to become THE implementation of IDEAS! Could you both have a look. Some documentation and further testing are missing, but I found Arnout's code pretty clean.

Let us wait for the feedback of A60 and then we can clean up the redundant models?

**Comment by damienpicard** [comment]
I wonder if the heat losses to environment make sense the way we implemented them. There are indeed compensated into the heatSource model and therefore they do not lead to an increase of power. Their only have an added value if the heat port is connected to a room and that the heat losses of the HP is considered as a gain to the room.

**Comment by damienpicard** [comment]
After discussion with Arnout, we decided to set the QLossesToCompensate = boiler temperature - TEnvironement.

TEnvironement is now a parameter instead of the heatPort variable. 

The new implementation can be found in the branch #Annex60_HP_review  which will be analysis by the other A60 partners.

**Comment by rubenbaetens** [comment]
I presume `QLossesToCompensate = h * (TBoiler - TEnvironement)` ... why not just make a boolean with or without heat port ?

**Comment by damienpicard** [comment]
@rubenbaetens The amount of heat that the boiler delivers to the water for different working conditions is given by the fabricant. However, this data already includes thermal losses as the experiments are done in a room with pressumly 20 degC. 

In order to know the absolute (e.g. fully isolated) amount of heat to the water, this thermal losses should be added to the one provided by the fabricant. These losses will then be cancelled out with the model thermal losses, if they happen at the same temperature TEnviromnent = 20 degC.

**Comment by rubenbaetens** [comment]
@damienpicard So you need a *guess* of the QHeatToCompensate at the working conditions of the fabricant data ?

**Comment by damienpicard** [comment]
@rubenbaetens Indeed, or rather of the TEnvironment, as QHeatToCompensate depends on your set point.

**Comment by rubenbaetens** [comment]
@damienpicard well, TEnvironment AND the insulation level, that's why i corrected the previous equation. And actually you also need TBoiler of the test, as this may have been done with a cold start or contrary.

**Comment by Mathadon** [comment]
To do: merge ```develop branch```, add verification/validation tests, document code with comments, info section.
@arnoutaertgeerts, @damienpicard  can you have a look at this?
Then I will review this!

**Comment by rubenbaetens** [comment]
@Mathadon @damienpicard This pull request dates back from 4 months ago, how far are we here ?

**Comment by Mathadon** [comment]
I need to review it but I haven't found the courage yet.. :(

**Comment by Mathadon** [comment]
I merged the develop branch into this branch, but there seem to be some bugs in the model.

I also have a question:
`IDEAS.Fluid.Production.HeatSources.Boiler` seems to have hard-coded table inputs for the temperature and mass flow rate. Since not all data sheets have these inputs, they may have other, should we not make this more generic?

**Comment by rubenbaetens** [comment]
Temperature v. mass flow rate in fact sounds like an odd data entry for a boiler.

**Comment by rubenbaetens** [comment]
I'm cursing on the use of `IDEAS.Fluid.Production.Boiler` and then remembered this pull request is still open which might solve all my mess to get what i want ... how far are we from pulling this ?

**Comment by Mathadon** [comment]
This will probably be superseded by #536

**Comment by Mathadon** [comment]
Let's get this out of our pull request list since this won't be merged any time soon.

**Pull request closed without merging**
