### PR TITLE
merged Annex60 commit 02b622016922eebd6b84bf534fccf877e98c2cb8

### PR DESCRIPTION
**Pull request by Mathadon**
This is for fixing some bugs

### CODE REVIEW

**Comment by Mathadon** [comment]
oops, still need to run unit tests

**Comment by rubenbaetens** [comment]
@mathadon there are a huge number of whitespace changes here, i don't know if that's a good thing. It's like all `package.order`files are changed for no reason in https://github.com/open-ideas/IDEAS/commit/f4ee0c060bfd15c2af49efb90af669b88f284c54 ?

**Comment by Mathadon** [comment]
Yes I did not bother to filter it manually.

The .order changes are because Michael sorted the components alphabetically by default and this has been ‘fixed’ for the first time now.

**Comment by Mathadon** [comment]
@rubenbaetens can you check this again?

**Pull request merged**
