### PR TITLE
Issue1054 en673

### LINKED ISSUE #1054: tool for validation window U value
According to EN 673.

Should be added.

### PR DESCRIPTION
**Pull request by Mathadon**
closes #1054 

@damienpicard can you review this?

### CODE REVIEW

**Comment by damienpicard** [comment]
it is not entirely clear to me how to use that model to validate U-values. In the example, QTra_design is significantly different for the 2 windows (84 and 76 W).

Could you maybe mention how to use it? And if it is a validation model, it might be useful to include it in the unit test?

**Comment by Mathadon** [comment]
The model is modified such that its implementation is more in line with the standard. The U value, computed as `Q/dT/A`, corresponds to the norm value.

**Comment by Mathadon** [comment]
@damienpicard I clarified the documentation and I have added the plot command.

**Comment by Mathadon** [comment]
#1083 must be merged first in order for the unit tests to pass

**Pull request merged**
