### PR TITLE
Issue571 adsolair

### LINKED ISSUE #571: Validated menerga air handling unit model
This issue is for adding the Menerga air handling unit model that I have been developing.

### PR DESCRIPTION
**Pull request by Mathadon**
this closes #571 
would be good if we can add this to 1.0

### CODE REVIEW

**Comment by damienpicard** [comment]
We should first discuss how to include this type of models in IDEAS. They are somewhat outside the scope of the library but I agree that they can be an added value for (some) user. We could have an IDEAS meeting before the release to discuss the last remaining points.

**Comment by Mathadon** [comment]
sounds like a good idea! before or after the other IDEAS meeting?

**Comment by damienpicard** [comment]
Before or during, as you prefer.

**Comment by Mathadon** [comment]
@damienpicard this is ready to be reviewed when you have time

**Comment by damienpicard** [comment]
@Mathadon 
your model does not have any icon...
image

**Comment by damienpicard** [comment]
@Mathadon it would be nice to add the unit to the datasheet output so that the plots use the same units for temperatures.

**Comment by damienpicard** [comment]
@Mathadon There is no example, only some validation models. Could you maybe add a simple example?

**Comment by damienpicard** [comment]
@Mathadon minor comment: the validation plots use another naming than the variable name. How do I find back the modelica variable?

**Comment by damienpicard** [comment]
@Mathadon once these comments are handled, the pull request can be merged.

**Comment by Mathadon** [comment]
Added example and icon.

If you click setup in the plot then you can see the variable names :)

**Pull request merged**
