### PR TITLE
added building shade implementation for OuterWall

### PR DESCRIPTION
**Pull request by Mathadon**
see #576 

@damienpicard can you review this? I still have to add an example model. This is not urgent.

### CODE REVIEW

**Comment by damienpicard** [comment]
@Mathadon this looks cool. Some remarks:

- [ ] We  should add unit tests though. 
- [ ] And  we may want to propagate it into RectangularZoneModel?
- [ ] We should probably also add an assert that it's not used for linearization (lideas), or support it.
- [ ] the assert with `-hWal` is too strict if the wall is not on the ground (for example wall of first floor). If L is large, their might still be some shading. But it's true that it's an unlikely case and with limited influence.

**Comment by Mathadon** [comment]
@damienpicard I added an assert for the building shade.
I agree that the assert is wrong. I'll remove it just to be sure!

**Comment by Mathadon** [comment]
The results seem correct upon closer inspection.

**Comment by damienpicard** [comment]
Thanks for the work :)

**Pull request merged**
