### PR TITLE
Issue879 lighting gains

### PR DESCRIPTION
**Pull request by icupeiro**
this solves #879

### CODE REVIEW

**Comment by icupeiro** [comment]
FIX-ME: still to-do, update documentation and revision history

**Comment by icupeiro** [comment]
@Mathadon to adapt: result files

**Comment by Mathadon** [comment]
@icupeiro can you add a .mos script for the new examples?

**Comment by icupeiro** [comment]
@Mathadon Travis Cl checks passed succesfully

**Comment by icupeiro** [comment]
@Mathadon new implementation ready for revision

**Comment by Mathadon** [comment]
@icupeiro this look really good. What source did you use for the luminous efficacy and the lux requirements?

**Comment by icupeiro** [comment]
@Mathadon 

For the lighting requirements I used standard EN 12464-1 (generic are though estimated)
For the split between radiative and convective fractions, I estimated them based on the Table from ASHRAE 2017 Fundamentals. Halogens where not included, but I took into account the fact that the filament temperature is higher than incandescent to increase a bit the radiative contribution.
For the luminous efficacy I quickly averaged some example values in a Table from Wikipedia, adequately referenced. 

https://en.wikipedia.org/wiki/Luminous_efficacy#Lighting_efficiency

I forgot to propagate the room type parameters... I will do now

**Comment by Mathadon** [comment]
@icupeiro I added the source of the luminance efficacy in the model documentation. Can you add the source for the Generic/Office illuminance too? And I think you forgot to remove some old files from the pull request. Once these issues are sorted and the unit tests pass, this can be merged!

**Comment by icupeiro** [comment]
@Mathadon I left the office to go language course. I'll have a look as soon as I get the office tomorrow

**Comment by icupeiro** [comment]
@Mathadon ready for merging once the unit tests pass

**Pull request merged**
