### PR TITLE
added JModelica support for #559

### PR DESCRIPTION
**Pull request by Mathadon**
@damienpicard this addresses your remarks in #559 
this version of the code works in `LIDEAS` too

still running unit tests

### CODE REVIEW

**Comment by Mathadon** [comment]
this can be merged

**Comment by Mathadon** [comment]
@damienpicard can you have another look at this?

**Comment by damienpicard** [comment]
@Mathadon I'll have a look at this either mid-May or beginning of June. Is that good for you?

**Comment by Mathadon** [comment]
ok!

**Comment by damienpicard** [comment]
@Mathadon , thanks for the changes, they are fine for me. I've updated the `LIDEAS` code as the changes I made to the code used for my MPC paper where not yet include. See https://gitlab.mech.kuleuven.be/u0091751/lideas/merge_requests/4.

Apparently, there are some merge conflicts. Could you have a quick look at it? Thx!

**Pull request closed without merging**
