### PR TITLE
Issue673 electric fixes

### PR DESCRIPTION
**Pull request by cprotopa**
This pull request addresses #673 and #721.

### CODE REVIEW

**Comment by cprotopa** [comment]
@Mathadon , the files that I deleted would end up to be the same as those found in the packages `AC` and `DC`, after fixing the errors. @rubenbaetens agreed they were not useful any more. I also checked that they are not used anywhere else.

**Comment by cprotopa** [comment]
Actually the changes in `Photovoltaics/Components/PvArray` should be reverted. The extra cosine blocks should be there. This is half of changes in commit d38240474ad59118a74636339c9243aa6ddbc115. How can I correct this? Push a new commit? Or..?

**Comment by Mathadon** [comment]
If it's half the changes in the commit then it's probably easiest to re-add the blocks manually and then push a new commit :)

**Comment by GlennReynders** [comment]
It still seems the implementation of the PV models is not ok with variables declared as angles which contain cosines of angles etc. I'll revise the implementation.

**Comment by GlennReynders** [comment]
We've checked the angles again (and again) and indeed the cosines should  be there, so the current implementation is ok (it can be improved though).

**Comment by GlennReynders** [comment]
closes issue #673

**Comment by Mathadon** [comment]
thanks!

**Pull request merged**
