### PR TITLE
Issue227 heat pump names

### PR DESCRIPTION
**Pull request by Mathadon**
Updated heat pump names to have a clearer library structure

Also made changes to HeatPump_events.mo model

### CODE REVIEW

**Comment by Mathadon** [comment]
This is for #227

**Comment by Mathadon** [comment]
I switched 2 ports so the media are mixed up.. Let me fix this first.

**Comment by rubenbaetens** [comment]
Is this supposed to be merged on ```develop``` or intentionally on ```master``` ?

**Comment by Mathadon** [comment]
should be develop.

**Pull request closed without merging**
