### PR TITLE
Issue591 linearization improvements

### PR DESCRIPTION
**Pull request by damienpicard**
Following improvements are done:
. in SimInfoManager, the different linearization flag such as `linExtCon` are set to `true` if linearize=`true`.
. obsolete parameter `placeCapacityAtSurf_b ` from `MonoLayerDynamic` is removed. `DynamicFreeInitial` is used instead when 2 capacities are connected to each other without resistance between them.
. in `BoundaryWall`, the input `T_in` and `Q_in` are now multiplied with `sim.dummy` such that the linearization does not make them zero when connected to a constant.
. in `slabOnGround`, the dynamics of the first layer of layMul (so connected to `port_a`) was set to `DynamicFreeInitial` instead of the last layer (connected to `port_b`). This is now corrected as  the initialization problem was due to the connection of `layMul.port_b` with `layGro.port_a`.
. `Qm` (heat flux from the ground) in `slabOnGround` is calculated by a now linear equation. The yearly average value is now used when `sim.linearize=true`.

### CODE REVIEW

**Comment by damienpicard** [comment]
@Mathadon I don't know why so many commits are visible. The file changes are very limited.

**Comment by Mathadon** [comment]
. in slabOnGround, the dynamics of the first layer of layMul (so connected to port_a) was set to DynamicFreeInitial instead of the last layer (connected to port_b). This is now corrected as the initialization problem was due to the connection of layMul.port_b with layGro.port_a.

This can still lead to problems. In cases where the first layer is a steady state layer. This should not appear when using the fix from d5d8e2c48e9e30a15b546f1a3ee14997629b732e . Can you apply this instead?

**Comment by Mathadon** [comment]
Did you run unit tests?

**Comment by damienpicard** [comment]
We can wait for #543, and afterwards run the unit tests.

**Comment by damienpicard** [comment]
@Mathadon it turned out that `placeSurfaceCapacity_b` was indispensible. See revision of boundaryWall and of slabOnGround for explanation (89e25c3)

**Comment by Mathadon** [comment]
this is superseded by #596

**Pull request closed without merging**
