### PR TITLE
added unit test that demonstrates zone air models

### PR DESCRIPTION
**Pull request by Mathadon**
added useFluPor parameter in structure

this is for #572

### CODE REVIEW

**Comment by Mathadon** [comment]
@GlennReynders can this be merged?

**Comment by GlennReynders** [comment]
why did you put `mSenFac=0.822` in thermal only model?

**Comment by Mathadon** [comment]
That's in an example that compares the default implementation with the thermal-only implementation. Case900 also has mSenFac=0.822 so that's the reason :)

**Comment by Mathadon** [comment]
@GlennReynders can you have another look at this?

**Pull request merged**
