### PR TITLE
Issue874 horizontal fins diffuse rad

### LINKED ISSUE #874: horizontal fin model do not take into account diffuse radiation
the model HorizontalFins.mo is not taking into account the effect on the diffuse radiation, hence causing a considerable mismatch

In plot
- Red is measured value
- Green is not taking into account the effect of diffuse radiation (as implemented)
- Blue is a using the same ratio for diffuse radiation as calculated for direct radiation
- Purple is the ambient temperature

The effect is more clearly seen in the weekend period (absence of ventilation and occupancy) where the effect of the afternoon sun produces those peaks in the green plot

image

### PR DESCRIPTION
**Pull request by icupeiro**
This fixes #874 

As commented in the issue, the proposed implementation would lead to algebraic loop if beta is a variable parameter. In this proposed implementation I only use 1 discretisation for the fin.

Checking with simulations, what I found interesting is that the diffuse shading fraction is linear (R^2=0.9951) compared to this beta angle for given values of transmittance and reflectance

@Mathadon how would you suggest to proceed with this?

### CODE REVIEW

**Comment by Mathadon** [comment]
@icupeiro this implementation looks like it should/could be simplified. It contains many equation relative to the accuracy increase that it brings. Do you have a reference/motivation for this implementation such that I can understand what you did? Then I may be able to propose some simplifications.

**Comment by icupeiro** [comment]
I am following Section 3.6.2 in https://windows.lbl.gov/sites/all/files/Downloads/venetian-technical-document.pdf with only 1 discretisation

For the view factors computation, I use the cross-string method http://www.mhtlab.uwaterloo.ca/courses/ece309/handouts/Spring16/HottelCrossedStrings.pdf

This factor is indeed dependent on the beta angle. I checked out that there is a linear correlation between the shading factor and the beta angle (for a determined value of transmittances and reflectances). In that sense I would suggest to look for a simple equation like 

difShaFac = a + b*beta

The question is how to compute a and b...

**Comment by Mathadon** [comment]
@icupeiro any progress on this?

**Comment by icupeiro** [comment]
not till that point, I will have a look after FCUs
Then we can discuss how to do implement this

**Comment by Mathadon** [comment]
@icupeiro can this be closed for now?

**Comment by icupeiro** [comment]
It can as the error I recall is not that high and current implementation would add algebraic loops

**Pull request closed without merging**
