### PR TITLE
Proposal on Issue417_treeStructure

### PR DESCRIPTION
**Pull request by rubenbaetens**
Hereby a pull request including all changes mentioned in https://github.com/open-ideas/IDEAS/issues/417 (including checked unittests).

I suggest it reviewed by @GlennReynders @damienpicard @Mathadon just to agree on the new structure.

### CODE REVIEW

**Comment by GlennReynders** [comment]
Some suggestions:
- Constants vs Types: still duplicates there.
- SimInfoManager also under BoundaryConditions
- PartialSimInfoManager under BoundaryCondtions.BaseClasses
- BoundaryConditions.[SkyTemperature:WeatherData] under BoundaryConditions.Climate.Meteo or BoundaryConditions.BaseClasses (but my preference under climate.meteo)

Is 'Circuits' a good name of an umbrella package of 'BaseCircuits' and 'Systems' ? Maybe we can use something like: 'HVAC' , 'Systems' or 'BaseSystems'

**Comment by rubenbaetens** [comment]
Updated location of (partial) SimInfoManager, but:

- Can't find any duplicate on Constants and Types
- Actually `BoundaryConditions.Meteo` should be obsolete and we better use the `BoundaryConditions.WeatherData.ReaderTMY3` from `Annex60`.

Additionally, i used the name `IDEAS.Circuits` as you can use the terminology for both hydraulic and electronic circuits (but i guess it also works with systems).

**Comment by Mathadon** [comment]
Will try to look into this, but I'm quite busy at the moment :(

**Comment by Mathadon** [comment]
A lot of files were removed and then added again (instead of removed). This leads to a lot of large diffs. Do you see a way to fix this? Could you also provide a description of what you changed? Are there models where the code changed or did you only reformat/rename stuff? I prefer not to go through diff of 700 files manually.. :p

**Comment by rubenbaetens** [comment]
I did not change code (except for renaming crossreferences to models due to) only moved files; and changeing the location of files always results in a deletion + creation of a file in git.

**Comment by rubenbaetens** [comment]
I notice we should (kinda) move forward with this rather fast. To give an example: i found a bug in a model that's moved in this pull request. Solving it in develop thus results in conflicts and/or the bug may stay unnoticed.

**Comment by Mathadon** [comment]
We should probably move `IDEAS.Fluid.Valves` to `IDEAS.Fluid.Actuators.Valves` ? Or even remove these models?

**Comment by Mathadon** [comment]
I propose to also remove:
- IDEAS.Fluid.FixedResistances.InsulatedPipe 
- IDEAS.Fluid.FixedResistances.Pipe
- IDEAS.Fluid.FixedResistances.Pipe_Insulated

**Comment by GlennReynders** [comment]
@Mathadon I agree with removing IDEAS.Fluid.Valves since all these are in similar form available in IDEAS.Fluid.Actuators.Valves
Also the pipes you stated indeed seem obsolete. 
I'll make the changes

**Comment by GlennReynders** [comment]
@rubenbaetens `IDEAS.Fluid.Valves.ThermostaticThreeWayValve` is used in most of the heating circuits. I propose to keep this component then and move it to 'IDEAS.Fluid.Actuators.Valves'

**Comment by rubenbaetens** [comment]
I re-pulled `develop` into this branch so this can be pulled once the comments raised here are adressed.

**Comment by rubenbaetens** [comment]
I re-pulled develop into this branch so this can be pulled once the comments raised here are adressed. That is:

- [ ] @Mathadon proposes to move `IDEAS.Fluid.Valves` to `IDEAS.Fluid.Actuators.Valves`  
- [ ] @Mathadon propose to remove `IDEAS.Fluid.FixedResistances.InsulatedPipe`
- [ ] @Mathadon propose to remove `IDEAS.Fluid.FixedResistances.Pipe`
- [ ] @Mathadon propose to remove `IDEAS.Fluid.FixedResistances.Pipe_Insulated`
- [ ] @GlennReynders proposes to move `IDEAS.Fluid.Valves.ThermostaticThreeWayValve` to `IDEAS.Fluid.Actuators.Valves`

**Comment by Mathadon** [comment]
@damienpicard @GlennReynders do you have some feedback for this?

**Comment by Mathadon** [comment]
@rubenbaetens can you merge develop into issue417_treeStructure?
You did not 'rename' files (you deleted and created new files) when restructuring the library such that conflicts don't get detected/resolved. :(

**Comment by rubenbaetens** [comment]
Actually when i pulled from `develop` it detected the differences last time. I don't think renaming solved that issue here, when you move files from directory.

**Comment by Mathadon** [comment]
It can still detect differences but the problem is for instance that you moved `RadSol` and I changed its implementation. But since you deleted `RadSol` and created a new one, my changes get applied to the 'old' `RadSol` which then immediately is deleted, leaving us with the old implementation of `RadSol` in a new location.

Is it a lot of work to redo the restructuring? I think it's a cleaner solution than manually trying to figure out what files need to be updated. And then we can also correctly 'rename' the models such that the git history of the file stays intact.

**Comment by rubenbaetens** [comment]
But last time i tried the *rename* option and it seems the git history was
still destroyed. Are you sure it works ?

**Comment by Mathadon** [comment]
I think it depends on what you want to use it for. I'm not entirely sure.

**Comment by damienpicard** [comment]
This pull request should be made again. We agreed that following changes must also be added:
- delete
. IDEAS.Fluid.FixedResistances.InsulatedPipe
. IDEAS.Fluid.FixedResistances.Pipe
. IDEAS.Fluid.FixedResistances.Pipe_Insulated

- Move
. all Fluid.Valve to Fluid.Actuator.Valves.Simplified

**Comment by damienpicard** [comment]
also check: https://github.com/open-ideas/IDEAS/issues/430

**Pull request closed without merging**
