### PR TITLE
Issue298 view factors

### PR DESCRIPTION
**Pull request by Mathadon**
This is for #298 

The new implementation is disabled by default. I added a comparison of the two implementations in the BesTest package. Unit test results added. 
Note that the new implementation is currently slower. However it becomes faster if states are located on the wall surface.

### CODE REVIEW

**Comment by Mathadon** [comment]
I need to check this with @rubenbaetens

**Comment by Mathadon** [comment]
This has been updated and is ready to merge: I added code that checks if all view factors sum up to 1

Make sure to look into https://github.com/open-ideas/IDEAS/pull/372 first since the above pull request includes code from #372

**Comment by Mathadon** [comment]
The difference between the two implementations is on the order of 0.05 K so it looks like the 'old' implementation uses a valid approximation. We can use this comparison as a validation exercise. 

Statistics are however different. 
Old implementation:
```
Sizes of linear systems of equations: {2, 2, 39, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}
Sizes after manipulation of the linear systems: {0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2}
Sizes of nonlinear systems of equations: {2, 6}
Sizes after manipulation of the nonlinear systems: {1, 2}

CPUtime: 107s
```

New implementation:
```
Sizes of linear systems of equations: {2, 2, 24, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}
Sizes after manipulation of the linear systems: {0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2}
Sizes of nonlinear systems of equations: {2, 6}
Sizes after manipulation of the nonlinear systems: {1, 2}
CPUtime: 144s
```
The performance penalty is somewhat unexpected.. It's probably caused because of the large amount of operations required for this implementation. So I would advice to stick with the existing implementation.

**Comment by rubenbaetens** [comment]
So all system of equations get smaller but cpu goes up ... Many of the operations are initial calculations, no ? But i guess it can't be just that as it would mean initialisation takes ages.

**Comment by Mathadon** [comment]
The reason is probably that there are more equations that need to be computed since the resistance is computed between each two surfaces instead of between each surface and a common node. Does that make sense?

Op 17-aug.-2015 om 16:32 heeft rubae <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


So all system of equations get smaller but cpu goes up ... Many of the operations are initial calculations, no ? But i guess it can't be just that as it would mean initialisation takes ages.

**Comment by damienpicard** [comment]
How is the heat gain from heatPortRad divided between the surfaces?

**Comment by damienpicard** [comment]
Is this necessary if a capacity is added to every zone surface?

**Comment by damienpicard** [comment]
This will be added conditionally once the heatPortRad for gain is solved.

**Pull request merged**
