### PR TITLE
Issue1220 BOPTEST Updates

### PR DESCRIPTION
**Pull request by dhblum**
This is for #1220.  In particular, it:

1. Updates documentation to add more illustrative schematics.
2. Updates bestest hydronic case to move heating set point offset to before overwrite block.

### CODE REVIEW

**Comment by dhblum** [comment]
@JavierArroyoBastida and @Mathadon Can you please take a look?  It also seems like I can't ask for an official review through the github gui, not sure why.

**Review by JavierArroyoBastida — APPROVED** [review]
@Mathadon this is looking good to me and I believe it can be merged.

**Comment by Mathadon** [comment]
> @JavierArroyoBastida and @Mathadon Can you please take a look? It also seems like I can't ask for an official review through the github gui, not sure why.

Probably because you don't have write access on the repo :) 

Running unit tests!

**Comment by dhblum** [comment]
Thanks @Mathadon  and @JavierArroyoBastida !

**Pull request merged**
