### PR TITLE
Issue392 multi gain

### PR DESCRIPTION
**Pull request by damienpicard**
This pull request solves #392 . It also removes the duplicated equations from internalWal, externalWall and slabOnGround to StateWallNoSol.

### CODE REVIEW

**Comment by damienpicard** [comment]
I havn't run the unit tests yet.

**Comment by Mathadon** [comment]
Is this change backwards compatible?

**Comment by damienpicard** [comment]
I indeed forgot to mention:

if you do not use the pre-made ConstructionType of IDEAS, you need to do the following changes:
1) put curly brackets `{}` around the value of `locGai` (in `ConstructionType`)
2) in the connections of your structure model, you might need to replace the `port_emb` by `port_emb[1]`

**Comment by Mathadon** [comment]
Probably best to check this with BWF first then

**Comment by damienpicard** [comment]
@cprotopa @GlennReynders @rubenbaetens what do you think of this proposition?

**Comment by rubenbaetens** [comment]
OK for me, but we'll need to check the examples than so that they work with the new notation.

**Comment by rubenbaetens** [comment]
If you update the example @damienpicard, i'll accept the pull request.

**Comment by Mathadon** [comment]
Please don't forget to run the unit tests :)

**Comment by damienpicard** [comment]
Everybody agrees to add this feature even thought it is not backward compatible. 
The heatport should also be made conditional.
Adapt documentation such that it is clear that the heat port is connected ot gainLocation layer port_b.

**Comment by rubenbaetens** [comment]
@damienpicard Is this ready to be merged ?

**Comment by damienpicard** [comment]
Something is wrong, the unit test give different results...

**Comment by damienpicard** [comment]
I'll investigate this.

**Comment by Mathadon** [comment]
Creating new pull request based on local branch.

**Pull request closed without merging**
