### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rubenbaetens**
Some bugs on the Borehole and Electrical Components have been solved in develop, which would be nice to be solved in the master too. As the develop-branch is unittest'ed, this shouldn't be an issue (?)

### CODE REVIEW

**Comment by Mathadon** [comment]
We should run the unit tests again first. Have you got them working on your pc yet?

**Comment by rubenbaetens** [comment]
Not yet, so ... i'll have an attempt this week, this pull request is not urgent so far ...

**Comment by Mathadon** [comment]
When #269 is pulled then all unit tests are ok except for ```StorageTank_DHW_HP.mo```. This example gives very different results. I'm not sure what causes this.

**Comment by rubenbaetens** [comment]
#269 is pulled, so this one canbe pulled too, or do we first want to solve the `StorageTank_DHW_HP.mo` ?

**Pull request merged**
