### PR TITLE
Issue152 grouped environment calculations

### PR DESCRIPTION
**Pull request by Mathadon**
This is for #152 
@rubenbaetens can you review this?

### CODE REVIEW

**Comment by Mathadon** [comment]
Maybe it would be best to include some sort of a validation model. I'll have a look at it when you agree to the rest of the changes.

**Comment by rubenbaetens** [comment]
@Mathadon the validation could be fairly simple: you put two BESTEST cases in a model, one rotated with an angle "offset_small" and check if you  get the same result on a "small" error.

**Comment by Mathadon** [comment]
I think I'll foresee a parameter for disabling the automatic calculation and then the comparison can be exact.

**Comment by rubenbaetens** [comment]
@Mathadon all looks correct her, do you first want to include the validation before pulling ?

**Comment by Mathadon** [comment]
yup I'll try to fix this after my deadline of tomorrow

**Comment by Mathadon** [comment]
I added the example but the unit tests are broken so I still need to run it and add unit tests.

**Comment by Mathadon** [comment]
Added validation test and reference results. Results were identical.

I merged develop back into this branch. Currently running unit tests.

**Comment by Mathadon** [comment]
I had to accept some small differences in reference results after merging develop branch.

**Comment by Mathadon** [comment]
@rubenbaetens can we finish this?

**Pull request merged**
