### PR TITLE
epsLw_a in material definition ...

### PR DESCRIPTION
**Pull request by rubenbaetens**
#324 Default definition of epsLw_a and epsLw_b. They are used in glazing systems, so we need to keep both but they can be defined without possible discrepancies now.

### CODE REVIEW

**Comment by Mathadon** [comment]
```ZoneExample``` produces warnings: `Default value for input epsLw_a depends on variable epsLw in function IDEAS.Buildings.Validation.Data.Materials.WoodSiding
This is not supported.` 

Can you have a look at this and run unit tests?

This may also be a good occasion to change
```
  iEpsLw_a = mats[1].epsLw;
  iEpsSw_a = mats[1].epsSw;
  iEpsLw_b = mats[nLay].epsLw;
  iEpsSw_b = mats[nLay].epsSw;
```

into 
```
  iEpsLw_a = mats[1].epsLw_a;
  iEpsSw_a = mats[1].epsSw_a;
  iEpsLw_b = mats[nLay].epsLw_b;
  iEpsSw_b = mats[nLay].epsSw_b;
```
in `IDEAS.Buildings.Components.BaseClasses.MultiLayerOpaque` etc

**Comment by rubenbaetens** [comment]
@Mathadon The error was caused because `epsLw`is defined `final` in the material properties, though i could'nt figure out why this should or could be a problem. All is fine now.

**Comment by rubenbaetens** [comment]
i added epsSw ...

**Comment by Mathadon** [comment]
Unit tests do not run.

**Comment by Mathadon** [comment]
@rubenbaetens @GlennReynders 
I suggest you have a look at the changes later on, just to be sure!

**Pull request merged**
