### PR TITLE
Issue45 boiler model replaces #191

### PR DESCRIPTION
**Pull request by rubenbaetens**
replaces #191

### CODE REVIEW

**Comment by damienpicard** [comment]
@arnoutaertgeerts Is this the last version of the boiler? Or are you still working on it?

**Comment by arnoutaertgeerts** [comment]
Yes, When I have the time :)

**Comment by damienpicard** [comment]
@arnoutaertgeerts @saroele it seems to me that this pull request had many commits which had nothing to do with the boiler implementation. I reverted them + resolved conflicts with the *develop branch*. Please make sure you do not introduce any unwanted / unnecessary changes. I hope I did not revert any wrong models.

**Comment by damienpicard** [comment]
@arnoutaertgeerts I've made a partial class for the temperature security control (avoiding overheating and undercooling) (see #258). This could be implemented in ProductionSource too, once the definitive shape is decided.

**Comment by rubenbaetens** [comment]
@damienpicard @Mathadon @arnoutaertgeerts @saroele gentleman, how is the 'unificiation' of the heatpump models et al. going ? I'm using the 'old' `HP_AirWater_TSet` but i noitce i get modulations between 100 and 600 percent which of course sounds wrong.

**Comment by arnoutaertgeerts** [comment]
Working on it :)
Op vr 6 feb. 2015 om 11:06 schreef rubae <notifications@github.com>

**Pull request closed without merging**
