### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Mathadon**
replaces #975

### CODE REVIEW

**Comment by Mathadon** [comment]
@MatthiVH your changes move more ports than what you mentioned in #974
E.g. the `propsBus` is moved. This causes Dymola to automatically readjust all connections that are made to a propsBus. Therefore all models in IDEAS would have to be updated and the connections in all models of our users will be modified by Dymola too. I rather not make this change unless there is a good reason for it (e.g. as indicated: when two ports are on top of each other). Is there a motivation for moving other ports than `ppm`?

**Comment by MatthiVH** [comment]
@Mathadon True, sorry about that, I said in my e-mail once this ppm port and a few minor other things.
Motivation: If you look at other components, they seem to be visually structured in a clear way (e.g. real inputs left, real outputs right and all more or less the same size). In the zone-component however, it's a little bit different. Lots of different connectors are concentrated on the right side, sized and organised differently. So as a user of IDEAS, building further on an extend of this component (to have more inputs/outputs (e.g. atmospheric pressure in the zone, additional trace substance concentrations) and make it suitable for a project), I felt like all connectors became a bit all over the place because there is no space to structure additional ones clearly/group them (even now, it's a little on the edge in my opinion). As I planned on making this commit for the ppm port, I moved some connectors as well in order to see if it would be possible to modify some of these positions as well. If not, I completely understand, it was more a try-out. Kind regards, Matthias

**Comment by Mathadon** [comment]
@damienpicard what do you think? Should we reorder the zone component inputs in the icon?

**Comment by damienpicard** [comment]
@MatthiVH @Mathadon sorry for my very late reply. I agree to move `ppm` from `TSensor`. Making the outputs and the inputs the same size also sounds good. However, I like the fact that the propsBus is on one side and the other inputs on the other side. Propsbus are always so full of connections that it is then difficult to connect the real inputs and outputs when they are next to each other.

In my opinion, the true mess is in `IDEAS.Buildings.Components.RectangularZoneTemplate` but I do not have a better proposition for the moment.

**Comment by Mathadon** [comment]
@MattiVH @damienpicard I'll make a new PR that just moves the output

**Pull request closed without merging**
