### PR TITLE
Issue268 borefield

### PR DESCRIPTION
**Pull request by Mathadon**
propagated mFactor
fixed translation issue

for #268

### CODE REVIEW

**Comment by damienpicard** [comment]
@rubenbaetens why do you close this issue and delete the branch??

**Comment by rubenbaetens** [comment]
@damienpicard accident-de-parcours, suddenly `develop` wwas gone, causing the pull requests to close for i-don't-know-which-reason.

**Comment by Mathadon** [comment]
@damienpicard can you have a look at this?

**Comment by Mathadon** [comment]
@damienpicard can you verify this?

**Comment by damienpicard** [comment]
@Mathadon I agree with your changes.

I also implemented a new boolean variable *dynFil* with which you can conditionally remove the thermal capacities of the filling material in the borehole. This remove then the small time constant.

I also added the possibility of simulation double U-tube heat exchanger. However, I'm not 100 % sure of the formula I used, even though the results coincide relativelly well with EED. I'm waiting for the answer of a mail to verify them.

I would then like to validate the model using your TRT.

Finally, I did not yet re-run the unit tests.

**Comment by Mathadon** [comment]
Unit tests need to be updated (see pull request) before I can check the results.

**Comment by Mathadon** [comment]
I need to merge develop, check unit tests and peer review.

**Comment by damienpicard** [comment]
@Mathadon I merged the develop, added and check unit tests. Do you still want to do some peer review or should we merge it?

**Pull request merged**
