### PR TITLE
readMatrix is not defined outside Dymola

### PR DESCRIPTION
**Pull request by tbeu**
Use ExternData.Functions.readMatrix instead

Sure it does to deal with writeMatrix, too, which just is not yet implemented. It likely will follow soon.

Please also notice that [ExternData](https://github.com/tbeu/ExternData) v2.0.0 is not yet released. This PR is just to check if you are generally interested to substitute Dymola built-in functions by a FOSS implementation.

### CODE REVIEW

**Comment by Mathadon** [comment]
What is the advantage over using Dymola's built-in function? Right now it seems to be preferable to use the built-in functions since then we do not depend on external libraries.

Does ExternData support hdf5?

**Comment by tbeu** [comment]
Simply the reason is to open IDEAS lib to other Modelica Simulation tools.

ExternData can support hdf5 in the sense of v7.3 MAT-files which are basically a hdf5-wrapper. Currently ExternData is not built with hdf5 support due to the size of the hdf5 lib. But it is possible if someone is asking for it.

**Comment by Mathadon** [comment]
Only some very specific models use these built-in functions, so I rather stick with the current implementation, which has the advantage of not requiring an external library. If/when users request this feature then we can reconsider.

Thank you for the suggestion!

I'm currently developing a tool that uses hdf5. For this I may look at ExternData in the future.

**Comment by saroele** [comment]
I would say that opening up IDEAS to other tools is a valuable goal.  If
the matrixreaders are one of the last hurdles I definitely support this
pull request, but if there are many other non-compliant models it may be a
low priority?

**Comment by tbeu** [comment]
@saroele I agree. Did not check what else hurdles exist. I am afraid there are plenty of them.

**Comment by tbeu** [comment]
> I'm currently developing a tool that uses hdf5.

@Mathadon I just want to point to [NcDataReader2](https://github.com/tbeu/netCDF-DataReader) Modelica library for netCDF file I/O. netCDF files are basically hdf5 wrapped files.

**Comment by Mathadon** [comment]
I did not realise that, thanks!

**Comment by tbeu** [comment]
FYI: writeMatrix is now also implemented.

**Comment by tbeu** [comment]
FYI: ExternData (>= v2.0.0) supports hdf5 (by means of v7.3 MAT-files).

**Comment by Mathadon** [comment]
@damienpicard this may be worth looking into when you have time!

**Pull request closed without merging**
