### PR TITLE
Issue1316 CI

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
This is for #1316. It adds a new `tests` folder with a Dockerfile and a Makefile to build an image with Dymola installed for testing. Note that, to build the image it is needed to have a Dymola installation file and a license. We may want to change the current Travis implementation to use GitHub actions instead and benefit this way from the [free tier](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions).

### CODE REVIEW

**Comment by JavierArroyoBastida** [comment]
I'm experiencing numerical differences in reference results as the case below:
image

This could be because we're using an updated version of Dymola or because of changes in the library since unit tests were last created (on 2022-08-02). @jelgerjansen FYI.

**Comment by JavierArroyoBastida** [comment]
In [this branch](https://github.com/JavierArroyoBastida/IDEAS/tree/issue1316_ci_testingv3) I implement the exact same testing suite from the latest official IDEAS release (`v3.0.0`) and get no disagreement in reference results for the test above (`IDEAS.Examples.PPD12`). This shows that the origin of the numerical differences does not come from the Dymola version but from the changes implemented since that release. That is also expected because there has not been systematic testing going on ever since. I'll update reference results but drop here comparison results for those tests that did not pass for our record.

**Comment by JavierArroyoBastida** [comment]
image
image
image

**Comment by JavierArroyoBastida** [comment]
image
image

**Comment by JavierArroyoBastida** [comment]
image

**Comment by JavierArroyoBastida** [comment]
image


Also:
image

**Comment by JavierArroyoBastida** [comment]
image

**Comment by JavierArroyoBastida** [comment]
image
image
image
image

**Comment by JavierArroyoBastida** [comment]
image

**Comment by JavierArroyoBastida** [comment]
image

image

**Comment by JavierArroyoBastida** [comment]
All reference results should be up to date now. The following table summarizes the number of regression tests per package, the approximate time it took to run the tests for that package, and whether the package required an update in reference results or not:
image

**Comment by JavierArroyoBastida** [comment]
At this point, all packages are passing the tests except for LIDEAS. Testing LIDEAS leads to the following:
image
See [here](https://github.com/open-ideas/IDEAS/actions/runs/4895211466/jobs/8740490937). 
However, the models are running in Dymola when I use the GUI.

**Comment by JavierArroyoBastida** [comment]
@jelgerjansen @Mathadon FYI: this implements a new test suite with GitHub Actions to benefit from the free tier. I'm still planning to implement a clean-up job and some documentation but feel free to review already if you'd like to.

**Comment by Mathadon** [comment]
great, nice work :)

**Comment by Mathadon** [comment]
great, nice work :)

**Comment by jelgerjansen** [comment]
@JavierArroyoBastida thanks a lot for all the work! I'll try to do the review by the end of this week.

Regarding LIDEAS: I'll have to check in more detail, but I remember that this package is not used any more. Am I correct at @Mathadon?

The change in reference results is likely due to a change in material properties (#1268). @Mathadon were there any other 'significant' changes since the last working CI runner that you can think of?

**Comment by Mathadon** [comment]
LIDEAS is not actively used by anybody that I am aware of.

There were some changes to the way that shading is implemented. Perhaps that's related.. But I'm not sure whether those models even use shading. I don't think so.

**Pull request merged**
